"""
Expandable question banks with tracking to avoid repetition
Questions are randomly selected and tracked to prevent repeats
"""

# ==================== QOTD QUESTIONS (Expandable) ====================
QOTD_QUESTIONS = [
    "What's your favorite childhood memory?",
    "If you could have dinner with anyone, dead or alive, who would it be?",
    "What's the best advice you've ever received?",
    "If you could live anywhere in the world, where would it be?",
    "What's your hidden talent?",
    "What's something you're really proud of?",
    "If you could master any skill instantly, what would it be?",
    "What's your favorite way to spend a weekend?",
    "What's the most interesting place you've ever visited?",
    "If you could time travel, would you go to the past or future?",
    "What's your comfort food?",
    "What's a book/movie that changed your perspective?",
    "What's your biggest fear and why?",
    "If you won the lottery, what's the first thing you'd do?",
    "What's your favorite season and why?",
    "What's something you wish you knew more about?",
    "What's your dream job?",
    "What's the best gift you've ever received?",
    "If you could have any superpower, what would it be?",
    "What's your favorite memory from this year?",
    "What's something that always makes you smile?",
    "What's your biggest accomplishment?",
    "If you could learn any language, which one?",
    "What's your favorite hobby?",
    "What's the most adventurous thing you've done?",
    "What's your go-to karaoke song?",
    "What's something you're currently learning?",
    "What's your favorite quote?",
    "If you could meet your younger self, what would you say?",
    "What's your favorite thing about yourself?",
]

# ==================== WOULD YOU RATHER ====================
WYR_QUESTIONS = [
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather live in the past or the future?",
    "Would you rather have unlimited money or unlimited time?",
    "Would you rather never use social media again or never watch another movie?",
    "Would you rather be able to talk to animals or speak all languages?",
    "Would you rather live without music or without movies?",
    "Would you rather be famous or be the best friend of someone famous?",
    "Would you rather explore space or the deep ocean?",
    "Would you rather always be 10 minutes late or 20 minutes early?",
    "Would you rather have a rewind button or a pause button for your life?",
    "Would you rather be able to read minds or see the future?",
    "Would you rather live in a world without problems or a world without challenges?",
    "Would you rather have free Wi-Fi wherever you go or free coffee?",
    "Would you rather be the funniest person or the smartest person?",
    "Would you rather never have to sleep or never have to eat?",
    "Would you rather live in a big city or a small town?",
    "Would you rather be a master chef or a master musician?",
    "Would you rather have a photographic memory or be able to forget anything?",
    "Would you rather always say what you think or never speak again?",
    "Would you rather be able to control fire or water?",
]

# ==================== CONVERSATION STARTERS ====================
CONVERSATION_STARTERS = [
    "What's the most interesting thing that happened to you this week?",
    "If you could learn any skill instantly, what would it be?",
    "What's your go-to comfort food?",
    "Share a fun fact about yourself!",
    "What's the last thing that made you laugh?",
    "What's your favorite way to relax?",
    "If you could visit any country, where would you go?",
    "What's your favorite childhood game?",
    "What's something you're looking forward to?",
    "What's the best concert or show you've been to?",
    "What's your favorite type of music?",
    "If you could have any pet, what would it be?",
    "What's your favorite holiday and why?",
    "What's something you've always wanted to try?",
    "What's your favorite thing to do on a rainy day?",
    "What's the best meal you've ever had?",
    "If you could switch lives with anyone for a day, who would it be?",
    "What's your favorite app on your phone?",
    "What's something that made you smile today?",
    "What's your dream vacation destination?",
]

# ==================== COMPLIMENTS ====================
COMPLIMENTS = [
    "You're an awesome friend!",
    "You light up the room!",
    "You're more helpful than you realize!",
    "You have a great sense of humor!",
    "You're a great listener!",
    "You're incredibly talented!",
    "You make a positive difference!",
    "You're one of a kind!",
    "You're a joy to be around!",
    "You're stronger than you think!",
    "You have impeccable manners!",
    "You're a great example to others!",
    "You're always learning and growing!",
    "You have a great taste!",
    "You're really courageous!",
]

# ==================== ROASTS (Friendly & SFW) ====================
ROASTS = [
    "You're like a software update. Whenever I see you, I think 'Not now.'",
    "I'd agree with you, but then we'd both be wrong.",
    "You bring everyone so much joy... when you leave the room.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'd explain it to you, but I left my crayons at home.",
    "You're not stupid; you just have bad luck when thinking.",
    "I'm jealous of people who don't know you.",
    "You're the reason the gene pool needs a lifeguard.",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're like Monday mornings - nobody likes you.",
    "I'd call you a tool, but that would imply you're useful.",
    "You're proof that even trash can be recycled.",
    "You have the perfect face for radio.",
    "You're like a participation trophy - everyone gets one, but nobody wants it.",
    "If I had a dollar for every smart thing you say, I'd be broke.",
    "You're like a broken pencil - pointless.",
    "I'd roast you, but my mom said I'm not allowed to burn trash.",
    "You're the human version of a typo.",
    "You're like a screen door on a submarine - completely useless.",
    "If brains were dynamite, you wouldn't have enough to blow your nose.",
    "You're about as useful as a chocolate teapot.",
    "You're like a white crayon - nobody knows why you exist.",
    "You're the reason they put instructions on shampoo bottles.",
    "You're like a slinky - not really good for anything, but you bring a smile when pushed down the stairs.",
    "You're living proof that evolution can go in reverse.",
    "You're like a loading screen that never finishes.",
    "If you were a spice, you'd be flour.",
    "You're the 'skip ad' button everyone's looking for.",
    "You're like a pop-up ad - annoying and nobody asked for you.",
    "You're the reason people use 'Do Not Disturb' mode.",
    "You're like a WiFi signal - weak and unreliable.",
    "If you were a vegetable, you'd be a cabbage.",
    "You're like a buffering video - nobody wants to wait for you.",
    "You're the human equivalent of a paper cut.",
    "You're like a speed bump - slowing everyone down.",
    "If you were a font, you'd be Comic Sans.",
    "You're like a group project - nobody wants to work with you.",
    "You're the reason people invented headphones.",
    "You're like a captcha - annoying and unnecessary.",
    "If you were a season, you'd be tax season.",
    "You're like a spam email - unwanted and repetitive.",
    "You're the 'reply all' person everyone hates.",
    "You're like a low battery warning - always showing up at the worst time.",
    "If you were a day of the week, you'd be Monday.",
    "You're like a traffic jam - frustrating and going nowhere.",
    "You're the reason people invented the mute button.",
    "You're like a plot hole in a bad movie.",
    "If you were a subject in school, you'd be homework.",
    "You're like a mosquito - small, annoying, and nobody likes you.",
    "You're the reason people say 'I have plans' when they don't.",
    "You're like a dead pixel on a screen - small but irritating.",
    "If you were a meal, you'd be cold leftovers.",
    "You're like a spoiler - ruining everything for everyone.",
    "You're the reason people pretend to be on their phones.",
    "You're like a flat tire - a total letdown.",
    "If you were a game, you'd be one nobody wants to play.",
    "You're like a wrong turn - taking everyone in the wrong direction.",
    "You're the reason people invented 'seen' receipts.",
    "You're like a bad haircut - embarrassing and hard to fix.",
    "If you were a drink, you'd be flat soda.",
    "You're like a plot twist nobody asked for.",
    "You're the reason people invented the block button.",
    "You're like a broken elevator - going nowhere fast.",
    "If you were a movie, you'd be a sequel nobody wanted.",
    "You're like a wrong answer on a test - disappointing.",
    "You're the reason people invented 'airplane mode.'",
    "You're like a typo in an important email.",
    "If you were a color, you'd be beige.",
    "You're like a dead end - leading nowhere.",
    "You're the reason people invented the snooze button.",
    "You're like a bad joke - nobody's laughing.",
    "If you were a book, you'd be one nobody finishes.",
    "You're like a broken promise - disappointing everyone.",
    "You're the reason people invented caller ID.",
    "You're like a wrong order at a restaurant.",
    "If you were a song, you'd be one everyone skips.",
    "You're like a rainy day at the beach.",
    "You're the reason people invented 'read' receipts.",
    "You're like a flat basketball - useless.",
    "If you were a holiday, you'd be April Fools' Day.",
    "You're like a broken clock - right twice a day by accident.",
    "You're the reason people invented the 'unsubscribe' button.",
    "You're like a wrong number - nobody wants to answer.",
    "If you were a plant, you'd be a weed.",
    "You're like a bad dream - forgettable.",
    "You're the reason people invented voicemail.",
    "You're like a burnt toast - ruined from the start.",
    "If you were a weather forecast, you'd always be wrong.",
    "You're like a broken promise - never delivered.",
    "You're the reason people invented the 'ignore' button.",
    "You're like a flat note in a song.",
    "If you were a puzzle, you'd be missing pieces.",
    "You're like a bad haircut - everyone notices.",
    "You're the reason people invented 'busy' status.",
    "You're like a wrong turn on a road trip.",
    "If you were a grade, you'd be an F.",
    "You're like a broken link - leading nowhere.",
    "You're the reason people invented the 'decline' button.",
    "You're like a cold shower - unwelcome.",
    "If you were a meme, you'd be outdated.",
    "You're like a wrong ingredient in a recipe.",
    "You're the reason people invented 'offline' mode.",
    "You're like a bad review - nobody wants to see it.",
    "If you were a sport, you'd be one nobody plays.",
    "You're like a wrong answer on Jeopardy.",
    "You're the reason people invented the 'hide' button.",
    "You're like a broken promise at a birthday party.",
    "If you were a superhero, your power would be disappointing people.",
    "You're like a wrong exit on the highway.",
    "You're the reason people invented 'away' messages.",
    "You're like a bad ending to a good story.",
    "If you were a flavor, you'd be plain.",
    "You're like a wrong key on a keyboard.",
    "You're the reason people invented the 'report' button.",
    "You're like a flat soda at a party.",
    "If you were a dance move, you'd be the one nobody does.",
    "You're like a wrong answer in a trivia game.",
    "You're the reason people invented 'private' mode.",
    "You're like a bad sequel to a great movie.",
    "If you were a pizza topping, you'd be anchovies.",
    "You're like a wrong turn in a maze.",
    "You're the reason people invented the 'spam' folder.",
    "You're like a broken toy - nobody wants to play with you.",
    "If you were a TV show, you'd be canceled after one episode.",
    "You're like a wrong note in a symphony.",
    "You're the reason people invented 'incognito' mode.",
    "You're like a bad haircut on picture day.",
    "If you were a dessert, you'd be sugar-free.",
    "You're like a wrong answer on a multiple choice test.",
    "You're the reason people invented the 'leave group' button.",
    "You're like a flat tire on a road trip.",
    "If you were a social media platform, you'd be MySpace.",
    "You're like a wrong ingredient in a smoothie.",
    "You're the reason people invented 'do not track.'",
    "You're like a bad photo - everyone wants to delete it.",
    "If you were a video game, you'd have terrible reviews.",
    "You're like a wrong turn in a GPS.",
    "You're the reason people invented the 'unfollow' button.",
    "You're like a broken pencil - no point.",
    "If you were a restaurant, you'd have one star.",
    "You're like a wrong answer on a game show.",
    "You're the reason people invented 'silent' mode.",
    "You're like a bad haircut before a big event.",
    "If you were a car, you'd be recalled.",
    "You're like a wrong number in a phone book.",
    "You're the reason people invented 'block all.'",
    "You're like a flat note at a concert.",
    "If you were a movie genre, you'd be boring documentary.",
    "You're like a wrong turn on a treasure map.",
    "You're the reason people invented 'hide posts.'",
    "You're like a bad joke at a comedy show.",
    "If you were a phone app, you'd be uninstalled.",
    "You're like a wrong answer in a spelling bee.",
    "You're the reason people invented 'mute notifications.'",
    "You're like a broken promise on New Year's Eve.",
    "If you were a candy, you'd be black licorice.",
    "You're like a wrong turn in a video game.",
    "You're the reason people invented 'restrict.'",
    "You're like a bad ending to a TV series.",
    "If you were a workout, you'd be skipped.",
    "You're like a wrong answer on a final exam.",
    "You're the reason people invented 'hide story.'",
    "You're like a flat basketball at a championship game.",
    "If you were a holiday, you'd be the one nobody celebrates.",
    "You're like a wrong ingredient in a cake.",
    "You're the reason people invented 'turn off notifications.'",
    "You're like a bad haircut in a yearbook photo.",
    "If you were a streaming service, you'd buffer constantly.",
    "You're like a wrong turn on a hiking trail.",
    "You're the reason people invented 'snooze all.'",
    "You're like a broken promise at Christmas.",
    "If you were a board game, you'd be one with missing pieces.",
    "You're like a wrong answer on Who Wants to Be a Millionaire.",
    "You're the reason people invented 'clear all.'",
    "You're like a flat tire before a vacation.",
    "If you were a concert, you'd be canceled.",
    "You're like a wrong turn on a delivery route.",
    "You're the reason people invented 'mark as spam.'",
    "You're like a bad photo filter.",
    "If you were a recipe, you'd be missing key ingredients.",
    "You're like a wrong answer on a crossword puzzle.",
    "You're the reason people invented 'disable comments.'",
    "You're like a broken promise on Valentine's Day.",
    "If you were a vacation, you'd be rained out.",
    "You're like a wrong turn in a corn maze.",
    "You're the reason people invented 'archive all.'",
    "You're like a flat soda at a wedding.",
    "If you were a video, you'd be unwatched.",
    "You're like a wrong answer on a history test.",
    "You're the reason people invented 'turn off read receipts.'",
    "You're like a bad haircut before prom.",
    "If you were a party, nobody would show up.",
    "You're like a wrong turn on a treasure hunt.",
    "You're the reason people invented 'delete all.'",
    "You're like a broken promise on a birthday.",
    "If you were a song, you'd be on nobody's playlist.",
    "You're like a wrong answer on a science quiz.",
    "You're the reason people invented 'hide all.'",
    "You're like a flat tire on the first day of a road trip.",
    "If you were a game, you'd be uninstalled immediately.",
    "You're like a wrong turn in a scavenger hunt.",
    "You're the reason people invented 'block sender.'",
    "You're like a bad ending to a book series.",
    "If you were a workout class, you'd be empty.",
    "You're like a wrong answer on a geography test.",
    "You're the reason people invented 'turn off all notifications.'",
    "You're like a broken promise at a wedding.",
    "If you were a restaurant dish, you'd be sent back.",
    "You're like a wrong turn on a bike ride.",
    "You're the reason people invented 'mute all.'",
    "You're like a flat basketball at the playoffs.",
    "If you were a TV channel, you'd have no viewers.",
    "You're like a wrong answer on a math test.",
    "You're the reason people invented 'disable all.'",
    "You're like a bad haircut in a family photo.",
    "If you were a concert ticket, you'd be refunded.",
    "You're like a wrong turn on a morning jog.",
    "You're the reason people invented 'unsubscribe all.'",
    "You're like a broken promise at graduation.",
    "If you were a podcast, you'd have no listeners.",
    "You're like a wrong answer on an English test.",
    "You're the reason people invented 'hide from timeline.'",
    "You're like a flat tire on moving day.",
    "If you were a movie trailer, you'd be skipped.",
    "You're like a wrong turn on a nature walk.",
    "You're the reason people invented 'block all notifications.'",
    "You're like a bad photo on social media.",
    "If you were a video game level, you'd be impossible and boring.",
    "You're like a wrong answer on a chemistry test.",
    "You're the reason people invented 'turn off everything.'",
    "You're like a broken promise at an anniversary.",
    "If you were a streaming show, you'd be canceled mid-season.",
    "You're like a wrong turn on a scenic drive.",
    "You're the reason people invented 'silence all.'",
    "You're like a flat soda at a birthday party.",
    "If you were a book, you'd be returned unread.",
    "You're like a wrong answer on a biology test.",
    "You're the reason people invented 'hide all posts.'",
    "You're like a bad haircut on the first day of school.",
    "If you were a concert, you'd have empty seats.",
    "You're like a wrong turn on a city tour.",
    "You're the reason people invented 'opt out of all.'",
    "You're like a broken promise at a reunion.",
    "If you were a recipe video, you'd be scrolled past.",
    "You're like a wrong answer on a physics test.",
    "You're the reason people invented 'disable everything.'",
    "You're like a flat tire on graduation day.",
    "If you were a social media post, you'd get zero likes.",
    "You're like a wrong turn on a food tour.",
    "You're the reason people invented 'mute forever.'",
    "You're like a bad ending to a video game.",
    "If you were a workout video, you'd be paused.",
    "You're like a wrong answer on a literature test.",
    "You're the reason people invented 'turn off all updates.'",
    "You're like a broken promise at a baby shower.",
    "If you were a movie, you'd go straight to DVD.",
    "You're like a wrong turn on a wine tour.",
    "You're the reason people invented 'block everything.'",
    "You're like a flat basketball at the finals.",
    "If you were a cooking show, you'd have no viewers.",
    "You're like a wrong answer on an art test.",
    "You're the reason people invented 'hide forever.'",
    "You're like a bad haircut in a wedding photo.",
    "If you were a concert tour, you'd be postponed indefinitely.",
    "You're like a wrong turn on a brewery tour.",
    "You're the reason people invented 'unsubscribe from everything.'",
    "You're like a broken promise at a retirement party.",
    "If you were a YouTube video, you'd be disliked.",
    "You're like a wrong answer on a music theory test.",
    "You're the reason people invented 'silence forever.'",
    "You're like a flat tire on your wedding day.",
    "If you were a podcast episode, you'd be skipped.",
    "You're like a wrong turn on a ghost tour.",
    "You're the reason people invented 'opt out forever.'",
    "You're like a bad photo in a professional portfolio.",
    "If you were a streaming movie, you'd be paused and never resumed.",
    "You're like a wrong answer on a philosophy test.",
    "You're the reason people invented 'disable forever.'",
    "You're like a broken promise at a housewarming.",
    "If you were a video game, you'd be returned for a refund.",
    "You're like a wrong turn on a historical tour.",
    "You're the reason people invented 'mute permanently.'",
    "You're like a flat soda at a graduation party.",
    "If you were a TV series, you'd be forgotten after one season.",
    "You're like a wrong answer on a psychology test.",
    "You're the reason people invented 'turn off permanently.'",
    "You're like a bad haircut in a professional headshot.",
    "If you were a concert performance, you'd be booed off stage.",
    "You're like a wrong turn on an architecture tour.",
    "You're the reason people invented 'block permanently.'",
    "You're like a broken promise at an engagement party.",
    "If you were a recipe, you'd be one nobody makes twice.",
    "You're like a wrong answer on a sociology test.",
    "You're the reason people invented 'hide permanently.'",
    "You're like a flat tire on your honeymoon.",
    "If you were a movie franchise, you'd be rebooted and still fail.",
    "You're like a wrong turn on a food festival.",
    "You're the reason people invented 'unsubscribe permanently.'",
    "You're like a bad ending to a beloved series.",
    "If you were a workout program, you'd be abandoned on day one.",
    "You're like a wrong answer on an economics test.",
    "You're the reason people invented 'silence permanently.'",
    "You're like a broken promise at a promotion party.",
    "If you were a streaming series, you'd be unwatched.",
    "You're like a wrong turn on a museum tour.",
    "You're the reason people invented 'opt out permanently.'",
    "You're like a flat basketball at the championship.",
    "If you were a cooking channel, you'd have no subscribers.",
    "You're like a wrong answer on a political science test.",
    "You're the reason people invented 'disable permanently.'",
    "You're like a bad haircut in a dating profile photo.",
    "If you were a concert series, you'd be canceled permanently.",
    "You're like a wrong turn on a chocolate factory tour.",
    "You're the reason people invented 'block all forever.'",
    "You're like a broken promise at a farewell party.",
    "If you were a video tutorial, you'd be thumbs-downed.",
    "You're like a wrong answer on an anthropology test.",
    "You're the reason people invented 'hide all forever.'",
    "You're like a flat tire on the day you get your license.",
    "If you were a social media account, you'd be deactivated.",
    "You're like a wrong turn on a safari tour.",
    "You're the reason people invented 'mute all forever.'",
    "You're like a bad photo that somehow made it to print.",
    "If you were a movie sequel, you'd ruin the original.",
    "You're like a wrong answer on a linguistics test.",
    "You're the reason people invented 'turn off all forever.'",
    "You're like a broken promise at a milestone celebration.",
    "If you were a streaming platform, you'd have no content worth watching.",
    "You're like a wrong turn that adds three hours to the trip.",
    "You're the reason people invented 'block all permanently.'",
    "You're like a flat soda that's been sitting out for days.",
    "If you were a video game character, you'd be the one everyone avoids.",
    "You're like a wrong answer that costs you the game.",
    "You're the reason people invented 'unsubscribe from all forever.'",
    "You're like a bad haircut that takes months to grow out.",
    "If you were a concert, you'd be the one with technical difficulties.",
    "You're like a wrong turn that leads to a dead end.",
    "You're the reason people invented 'silence all permanently.'",
    "You're like a broken promise that nobody forgets.",
    "If you were a recipe, you'd be the one that never turns out right.",
    "You're like a wrong answer on the easiest question.",
    "You're the reason people invented 'opt out of all permanently.'",
    "You're like a flat tire that can't be fixed.",
    "If you were a TV show finale, you'd disappoint everyone.",
    "You're like a wrong turn on the way to something important.",
    "You're the reason people invented 'disable all permanently.'",
    "You're like a bad photo that becomes a meme.",
    "If you were a video game, you'd be the worst-rated one ever.",
    "You're like a wrong answer that everyone remembers.",
    "You're the reason people invented 'hide all permanently.'",
    "You're like a broken promise on the most important day.",
    "If you were a streaming service, you'd be the one nobody subscribes to.",
    "You're like a wrong turn that ruins the entire trip.",
    "You're the reason people invented 'mute everything forever.'",
    "You're like a flat soda at the most important celebration.",
    "If you were a concert tour, you'd be the one nobody attends.",
    "You're like a wrong answer that costs you everything.",
    "You're the reason people invented 'turn off everything forever.'",
    "You're like a bad haircut that ruins all your photos.",
    "If you were a movie, you'd be the one everyone walks out of.",
    "You're like a wrong turn that nobody can recover from.",
    "You're the reason people invented 'block everything forever.'",
    "You're like a broken promise that changes everything.",
    "If you were a recipe, you'd be the disaster everyone talks about.",
    "You're like a wrong answer on the final question.",
    "You're the reason people invented 'unsubscribe from everything forever.'",
    "You're like a flat tire on the most important journey.",
    "If you were a TV series, you'd be the one that should never have been made.",
    "You're like a wrong turn that becomes a cautionary tale.",
    "You're the reason people invented 'silence everything permanently.'",
    "You're like a bad photo that defines your entire year.",
    "If you were a video game, you'd be the one used as an example of what not to do.",
    "You're like a wrong answer that becomes legendary for all the wrong reasons.",
    "You're the reason people invented 'opt out of everything forever.'",
    "You're like a broken promise that nobody ever forgets.",
    "If you were a streaming show, you'd be the one that gets mocked for years.",
    "You're like a wrong turn that adds 'never go there' to the map.",
    "You're the reason people invented 'disable everything forever.'",
    "You're like a flat soda that somehow gets worse over time.",
    "If you were a concert, you'd be the one people demand refunds for.",
    "You're like a wrong answer so bad it becomes a teaching moment.",
    "You're the reason people invented 'hide everything forever.'",
    "You're like a bad haircut that becomes your permanent nickname.",
    "If you were a movie franchise, you'd be the reason they stopped making sequels.",
    "You're like a wrong turn that gets added to 'worst mistakes' lists.",
    "You're the reason people invented 'mute all notifications forever.'",
    "You're like a broken promise that ruins relationships.",
    "If you were a recipe, you'd be the one with warning labels.",
    "You're like a wrong answer that makes it into textbooks as an example.",
    "You're the reason people invented 'turn off all notifications forever.'",
    "You're like a flat tire that somehow deflates everyone's mood.",
    "If you were a TV show, you'd be the one that gets canceled and nobody notices.",
    "You're like a wrong turn that becomes an urban legend.",
    "You're the reason people invented 'block all notifications forever.'",
    "You're like a bad photo that gets framed as a joke.",
    "If you were a video game, you'd be the one speedrunners avoid.",
    "You're like a wrong answer so memorable it overshadows everything else.",
    "You're the reason people invented 'unsubscribe from all notifications forever.'",
    "You're like a broken promise that gets brought up at every family gathering.",
    "If you were a streaming platform, you'd be the one that goes bankrupt.",
    "You're like a wrong turn that requires a complete restart.",
    "You're the reason people invented 'silence all notifications permanently.'",
    "You're like a flat soda that somehow manages to be worse than water.",
    "If you were a concert series, you'd be the one that bankrupts the venue.",
    "You're like a wrong answer that changes the entire course of history.",
    "You're the reason people invented 'opt out of all notifications forever.'",
    "You're like a bad haircut that requires a hat for months.",
    "If you were a movie, you'd be the one that ends careers.",
    "You're like a wrong turn that adds days to the journey.",
    "You're the reason people invented 'disable all notifications permanently.'",
    "You're like a broken promise that becomes a life lesson.",
    "If you were a recipe, you'd be the one that gets banned from cookbooks.",
    "You're like a wrong answer that gets its own Wikipedia page.",
    "You're the reason people invented 'hide all notifications forever.'",
    "You're like a flat tire that somehow punctures everyone's plans.",
    "If you were a TV series finale, you'd be the one that ruins the entire show.",
    "You're like a wrong turn that becomes a documentary about what not to do.",
    "You're the reason people invented every 'disable' button ever made.",
]

# ==================== SONGS FOR GUESSING ====================
SONGS = [
    # Pakistani Classics
    {"lyrics": "Dil dil Pakistan, jaan jaan Pakistan", "answer": "Dil Dil Pakistan"},
    {"lyrics": "Aye watan pyare watan pak watan", "answer": "Aye Watan Pyare Watan"},
    {"lyrics": "Mera bichra yaar mujhe aaj mil gaya", "answer": "Mera Bichra Yaar"},
    {"lyrics": "Dil ki lagi na mano", "answer": "Dil Ki Lagi"},
    {"lyrics": "Tera woh pyar yaad hai mujhe", "answer": "Tera Woh Pyar"},

    # Pakistani Modern
    {"lyrics": "Aadat si hai mujhko aise jeene mein", "answer": "Aadat"},
    {"lyrics": "Tera mera rishta purana", "answer": "Tera Mera Rishta"},
    {"lyrics": "Sayonee mere dil ki", "answer": "Sayonee"},
    {"lyrics": "Duur na jaana", "answer": "Duur"},
    {"lyrics": "Khudi ko kar buland itna", "answer": "Khudi"},

    # Indian Classics
    {"lyrics": "Mere sapno ki rani kab aayegi tu", "answer": "Mere Sapno Ki Rani"},
    {"lyrics": "Yeh dosti hum nahi todenge", "answer": "Yeh Dosti"},
    {"lyrics": "Kabhi kabhi mere dil mein khayal aata hai", "answer": "Kabhi Kabhi"},
    {"lyrics": "Tum hi ho bandhu sakha tumhi", "answer": "Tum Hi Ho"},
    {"lyrics": "Lag ja gale ke phir ye haseen raat ho na ho", "answer": "Lag Ja Gale"},

    # Indian Modern/Bollywood
    {"lyrics": "Tum hi ho tum hi ho zindagi ab tum hi ho", "answer": "Tum Hi Ho"},
    {"lyrics": "Tujhe dekha to ye jaana sanam", "answer": "Tujhe Dekha To"},
    {"lyrics": "Chaiyya chaiyya chaiyya chaiyya", "answer": "Chaiyya Chaiyya"},
    {"lyrics": "Kal ho naa ho kal ho naa ho", "answer": "Kal Ho Naa Ho"},
    {"lyrics": "Kuch kuch hota hai tum nahi samjhoge", "answer": "Kuch Kuch Hota Hai"},

    # Famous English Songs
    {"lyrics": "I'm walking on sunshine, whoa oh", "answer": "Walking on Sunshine"},
    {"lyrics": "Is this the real life? Is this just fantasy?", "answer": "Bohemian Rhapsody"},
    {"lyrics": "Just a small town girl, living in a lonely world", "answer": "Don't Stop Believin'"},
    {"lyrics": "I got the eye of the tiger, a fighter", "answer": "Eye of the Tiger"},
    {"lyrics": "We will, we will rock you", "answer": "We Will Rock You"},
    {"lyrics": "Hello from the other side", "answer": "Hello"},
    {"lyrics": "Cause baby you're a firework", "answer": "Firework"},
    {"lyrics": "I'm gonna swing from the chandelier", "answer": "Chandelier"},
    {"lyrics": "Shake it off, shake it off", "answer": "Shake It Off"},
    {"lyrics": "We found love in a hopeless place", "answer": "We Found Love"},
    {"lyrics": "I will always love you", "answer": "I Will Always Love You"},
    {"lyrics": "Sweet dreams are made of this", "answer": "Sweet Dreams"},
    {"lyrics": "Don't stop me now, I'm having such a good time", "answer": "Don't Stop Me Now"},
    {"lyrics": "Imagine all the people living life in peace", "answer": "Imagine"},
    {"lyrics": "Hey Jude, don't make it bad", "answer": "Hey Jude"},
]

# ==================== URDU POETRY ====================
URDU_POETRY = [
    "دل کی ویرانی کا کیا مذکور ہے\nیہ نگر سو مرتبہ لوٹا گیا",
    "محبت کرنے والے کم نہ ہوں گے\nتری محفل میں لیکن ہم نہ ہوں گے",
    "ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے\nبہت نکلے مرے ارمان لیکن پھر بھی کم نکلے",
    "کبھی ہم خوب تھے، کبھی ہم خوب تھے\nکبھی ہم خوب تھے، کبھی ہم خوب تھے",
    "یہ دنیا اگر مل بھی جائے تو کیا ہے\nیہ دنیا اگر مل بھی جائے تو کیا ہے",
]

# ==================== PICTIONARY WORDS ====================
PICTIONARY_WORDS = [
    "cat", "dog", "house", "tree", "car", "sun", "moon", "star",
    "flower", "book", "phone", "computer", "pizza", "burger", "cake",
    "guitar", "piano", "drum", "rainbow", "cloud", "mountain", "beach",
    "bicycle", "airplane", "boat", "train", "elephant", "lion", "bird",
    "fish", "butterfly", "spider", "snake", "turtle", "rocket", "castle"
]

# ==================== PETS ====================
PETS = ["🐶 Dog", "🐱 Cat", "🐰 Rabbit", "🐹 Hamster", "🐦 Bird",
        "🐠 Fish", "🐢 Turtle", "🦎 Lizard", "🐷 Pig", "🐸 Frog"]

# ==================== COLLECTIBLE ITEMS ====================
ITEMS = ["🍎 Apple", "🍕 Pizza", "💎 Diamond", "🎁 Gift Box", "⚔️ Sword",
         "🛡️ Shield", "🏹 Bow", "🔮 Crystal Ball", "📿 Amulet", "👑 Crown",
         "🎨 Paint Brush", "📚 Ancient Book", "🗝️ Golden Key", "💰 Treasure Chest"]

def get_random_question(question_list, asked_list, max_history=50):
    """
    Get a random question that hasn't been asked recently
    Resets history if all questions have been used
    """
    available = [q for q in question_list if q not in asked_list]

    if not available:
        # All questions used, reset history
        asked_list.clear()
        available = question_list

    question = random.choice(available)
    asked_list.append(question)

    # Keep only last N questions in history
    if len(asked_list) > max_history:
        asked_list.pop(0)

    return question
